import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chess Agency",
  description: "Generated by Patryk",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="./favicon/faviconi.png?<generated>" type="image/png" sizes="32x32" />


        
          
        
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
